### ISSUE TITLE
is discard_all! working on version 1.1.0 

### ISSUE THREAD

**Issue by Mahinour-elsheikh** [jhawthorn/discard#71]
**Describe the bug**
When i used the discard_all! on relation   i got the following exception

> #<NoMethodError: undefined method `discard_all!' for #<ConversationMessage::ActiveRecord_Relation:0x00000000046a1748>\nDid you mean?  discarded>",

**To Reproduce**
Model:

```
class ConversationMessage < ApplicationRecord
    include Discard::Model
    belongs_to :conversation
end

```

the relation that reproduced the bug: 
`ConversationMessage.where(conversation_id: params[:id]).discard_all!
`
**Expected behavior**
to work normally

**Comment by jarednorman** [comment]
That feature is [unreleased](https://github.com/jhawthorn/discard/blob/master/CHANGELOG.md#unreleased) and will be in the next release.

**Comment by jarednorman** [comment]
I just cut version v1.2.0 which now supports it!
